### ISSUE TITLE
unsupported operand type(s) for +: 'dict_items' and 'list' when train

### ISSUE THREAD

**Issue by khcy82dyc** [jed-frey/DIGITS#3]
Hi @jed-frey , thank you so much for your work, as a windows+python3 user I'm trying to use digits and you saved the day!
I'm been setting up the digits and already sortted out lots of lots of small issues due to compatibility, until when i'm trying to train a image segmentation model using a customised network, I got 
unsupported operand type(s) for +: 'dict_items' and 'list' show in my browser when i click the 'create' button.
I looked on the web and realised it must be the python2->python3 but the issue is I don't see any error message to point out where it generated this error. do you might know which file is possibly generating this error?
Thanks!

**Comment by jed-frey** [comment]
Can you run digits with debugging turned on?

```digits-devserver --debug```

Then paste the full stack of the debug error.

I'll admit I haven't made it to the Image Segmentation examples. I know the error I just need to know where to find it.

**Comment by khcy82dyc** [comment]
AHA I totally forgot there is a debug mode, thanks a lot for this.
the error msg I got now is:
TypeError
unsupported operand type(s) for +: 'dict_items' and 'list'

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\DIGITS1a\digits\digits\webapp.py", line 82, in decorated
    return f(*args, **kwargs)
  File "C:\Projects\DIGITS1a\digits\digits\utils\auth.py", line 55, in decorated
    return f(*args, **kwargs)
  File "C:\Projects\DIGITS1a\digits\digits\model\images\generic\views.py", line 107, in create
    sweeps = [dict(s.items() + [('batch_size', bs)]) for bs in form.batch_size.data for s in sweeps[:]]
  File "C:\Projects\DIGITS1a\digits\digits\model\images\generic\views.py", line 107, in 
    sweeps = [dict(s.items() + [('batch_size', bs)]) for bs in form.batch_size.data for s in sweeps[:]]
TypeError: unsupported operand type(s) for +: 'dict_items' and 'list'

**Comment by jed-frey** [comment]
Pull and update to the latest master and see how that works.

**Comment by khcy82dyc** [comment]
it worked. thanks!!
